substitutions:
  my_name: "Bluetooth Proxy Ground"

packages:
  wifi: !include modules/common/wifi.yaml
  bluetooth: !include modules/common/bluetooth_tracker.yaml

esphome:
  name: kjokken-1-hub-c3
  friendly_name: ${my_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "VHFd/P8Y2MGssIQ93HE/Sn+iJXQpNG2S9NOH5zrDs3w="

ota:
  - platform: esphome
    password: "e4a7f5103e24617205e91f7f96c08720"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

captive_portal:

external_components:
  - source: github://dentra/esphome-components

binary_sensor:
  - platform: miot_mccgq02hl
    mac_address: "E4:AA:EC:51:21:7F"
    bindkey: "e7d7496bce21b73c875e77daecaf15b5"
    name: "Kjøkkenvindu Door/Window Sensor"
    light:
      name: "Kjøkkenvindu Light"
    alert:
      name: "Kjøkkenvindu Alert"
    battery_level:
      name: "Kjøkkenvindu Battery Level"
    battery_voltage:
      name: "Kjøkkenvindu Battery Voltage"

    