esphome:
  name: "stua-1-tempsensor"
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home.arpa
  fast_connect: true
  power_save_mode: light

#deep_sleep:
#  run_duration: 5s
#  sleep_duration: 55s


mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

sensor:
  - platform: dht
    pin: D2
    model: AM2302
    temperature:
      name: "temperature2"
    humidity:
      name: "humidity2"
    update_interval: 180s
  - platform: wifi_signal
    name: "WiFi Signal Stua"
    update_interval: 60s


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TbTyLSDB1lRFCSuyyNYfy0c0opBm7ZZs55BZlZ8XMUs="

ota:
  - platform: esphome
    password: "BMiNB3w9"
# Teste Deep Sleep
#deep_sleep:
#  run_duration: 10s
#  sleep_duration: 10min

    